/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class MonsterTest {
  @Test
  public void monsterToString() {
    App classUnderTest = new App();
    assertNotNull("monster should have a string", classUnderTest.toString());
  }

}
